name: ran_crm
description: RAN CRM - A shared contact and call log CRM app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.4.3

  # Secure storage for JWT
  flutter_secure_storage: ^9.2.2

  # State management
  provider: ^6.1.2

  # Local database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Contact and call log reading
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1
  call_log: ^6.0.1

  # Date/time formatting
  intl: ^0.20.2

  # Settings storage
  shared_preferences: ^2.2.3

  # URL launcher for call and SMS
  url_launcher: ^6.2.6

  # Device info for system settings
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
